/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by `convex dev`.
 * To update, run `convex dev`.
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as activities from "../activities";
import type * as tasks from "../tasks";
import type * as search from "../search";

/**
 * A utility for referencing Convex functions in your app.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.activities.logActivity;
 * ```
 */
declare const fullApi: ApiFromModules<{
  activities: typeof activities;
  tasks: typeof tasks;
  search: typeof search;
}>;

export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
