/* eslint-disable */
/**
 * Generated `server` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by `convex dev`.
 * To update, run `convex dev`.
 */

import type { ApiFromModules } from "convex/server";
import type * as schema from "../schema";

export type DataModel = ApiFromModules<typeof schema>;
export declare const schema: typeof schema;
